[tox]
envlist = linters
minversion = 2.9
skipsdist = True
sitepackages=False

[testenv]
install_command = pip install -U \
    {opts} {packages} \
    -c{env:TOX_CONSTRAINTS_FILE:https://opendev.org/starlingx/root/raw/branch/master/build-tools/requirements/debian/upper-constraints.txt}
setenv =
   VIRTUAL_ENV={envdir}
   OS_STDOUT_CAPTURE=1
   OS_STDERR_CAPTURE=1
   OS_DEBUG=1
   OS_LOG_CAPTURE=1
deps =
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
allowlist_externals =
  bash
passenv =
    XDG_CACHE_HOME


[testenv:bashate]
# Treat all E* codes as Errors rather than warnings using: -e 'E*'
commands =
  bash -c "find {toxinidir}                   \
         -not \( -type d -name .?\* -prune \) \
         -type f                              \
         -not -name \*~                       \
         -not -name \*.md                     \
         -name \*.sh                          \
         -print0 | xargs -r -n 1 -0 bashate -v \
         -e 'E*'"

[testenv:linters]
commands =
    {[testenv:bashate]commands}

[testenv:flake8]
basepython = python3
description = Dummy environment to allow flake8 to be run in subdir tox

[testenv:py39]
basepython = python3
description = Dummy environment to allow pylint to be run in subdir tox

[testenv:pylint]
basepython = python3
description = Dummy environment to allow pylint to be run in subdir tox

[testenv:metadata]
basepython = python3
description = Dummy environment to allow sysinv-app to be run in subdir tox

[testenv:bandit]
basepython = python3
description = Dummy environment to allow bandit to be run in subdir tox

[testenv:bandit-trixie]
basepython = python3
description = Dummy environment to allow bandit-trixie to be run in subdir tox

[testenv:coverage]
basepython = python3
description = Run coverage analysis via subdir tox
allowlist_externals = bash
                      tox
commands =
  bash -c "mkdir -p {toxinidir}/UTCoverage"
  bash -c "cd python3-k8sapp-kubevirt/k8sapp_kubevirt && tox -e coverage 2>&1 | tee {toxinidir}/UTCoverage/coverage_report.txt"

[testenv:py313]
basepython = python3
description = Dummy environment to allow py313 to be run in subdir tox

[testenv:flake8-trixie]
basepython = python3
description = Dummy environment to allow flake8-trixie to be run in subdir tox

[testenv:pylint-trixie]
basepython = python3
description = Dummy environment to allow pylint-trixie to be run in subdir tox

[testenv:metadata-trixie]
basepython = python3
description = Dummy environment to allow metadata-trixie to be run in subdir tox

[testenv:coverage-trixie]
basepython = python3
description = Run coverage-trixie analysis via subdir tox
allowlist_externals = bash
                      tox
commands =
  bash -c "mkdir -p {toxinidir}/UTCoverage"
  bash -c "cd python3-k8sapp-kubevirt/k8sapp_kubevirt && tox -e coverage-trixie 2>&1 | tee {toxinidir}/UTCoverage/coverage_report.txt"