# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2022-2023, 2025-2026 Wind River Systems, Inc.
#
#
# All Rights Reserved.
#    - Auto Updated Contents 2025-12-26 14:49:07 -
apiVersion: v2
appVersion: 1.5.1
description: A Helm chart for KubeVirt
name: kubevirt-app
type: application
version: 1.5.1
