# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
#    - Auto Updated Contents 2025-04-11 18:08:12 -

---
apiVersion: v2
appVersion: 1.5.0
description: A Helm chart for KubeVirt
name: kubevirt-app
type: application
version: 1.5.0
