certificateRotate:
  ca:
    duration: 1440h
    renewBefore: 720h
  server:
    duration: 1440h
    renewBefore: 720h
componentType: platform
useEmulation: false
containerPorts:
  metricsPort: 8443
  webhooksPort: 8444
featureGates:
  - Snapshot
imagePullSecrets: default-registry-key
images:
  tags:
    virtApiImage: quay.io/kubevirt/virt-api:v1.8.2
    virtControllerImage: quay.io/kubevirt/virt-controller:v1.8.2
    virtCtlImage: docker.io/starlingx/stx-kubevirt-app:stx.13.0-v1.8.2-2-trixie
    virtHandlerImage: quay.io/kubevirt/virt-handler:v1.8.2
    virtLauncherImage: quay.io/kubevirt/virt-launcher:v1.8.2
    virtOperatorImage: quay.io/kubevirt/virt-operator:v1.8.2
readinessProbePort: 8443
replicas: 1
resources:
  requests:
    memory: 400Mi
version: v1.8.2
