#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# All Rights Reserved.
#
#    - Auto Updated Contents 2025-04-11 18:08:12 -

ARG BASE
FROM ${BASE}
ADD https://github.com/kubevirt/kubevirt/releases/download/v1.5.0/virtctl-v1.5.0-linux-amd64 .
RUN chmod a+rwx ./virtctl-v1.5.0-linux-amd64
