# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2022-2023, 2025-2026 Wind River Systems, Inc.
#
#
# All Rights Reserved.
#    - Auto Updated Contents 2026-02-04 13:05:31 -
ARG BASE
FROM ${BASE}
ADD https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/virtctl-v1.7.0-linux-amd64 .
RUN chmod a+rwx ./virtctl-v1.7.0-linux-amd64
